### PR TITLE
Release 425

### PR DESCRIPTION
**Pull request by odockal**

### CODE REVIEW

**Comment by ajdor** [comment]
FYI, the CI tests do not reflect the state of the framework due to https://github.com/redhat-developer/vscode-extension-tester/blame/master/test/test-project/package.json#L135
I believe it should be reverted back to `*test.js`

**Comment by odockal** [comment]
@ajdor nice catch! Thanks!

**Review by djelinek — APPROVED** [review]

**Comment by ajdor** [comment]
The failures seen in the CI tests are similar to the issue reported in https://github.com/redhat-developer/vscode-extension-tester/issues/433, contextual menus in text editors cannot be retrieved.
This is probably due to VSCode upgrading to Electron 17 and being based on Chromium 98.

The chromedriver version pulled is 98 instead of 91 previously. In that version, the ShadowDOM element in which the context menu resides cannot be used as the enclosing item from which the ContextMenu object can be constructed.
The constructor in `AbstractElement` throws an exception `invalid locator` in line 30 since the ShadowDOM is not an instance of `WebElement` and selenium-driver cannot find it directly starting the lookup from the top element.

**Comment by odockal** [comment]
@ajdor Wow, I see, well, thanks for showing some direction. Though, I will definitely need more time to work on this change, so I have created https://github.com/redhat-developer/vscode-extension-tester/issues/440 to incorporate the changes, it might require upgrades to selenium-webdriver and types/selenium-webdriver so probably new major version will be needed.
I intend to release support for vscode 1.65.

**Pull request merged**
