### PR TITLE
Update ActionConstructor for ViewTitlePart

### LINKED ISSUE #605: [🚫 Bug] ExtensionsView take action function does not find proper action by its locator
> Define issue title **short** and **most specific** to the problem.
```
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//a[@title='Clear Extensions Search Results']"}
  (Session info: chrome=102.0.5005.167)
```

## Expected Behavior
```await titlePart.getAction('Clear Extensions Search Results');```

## Actual Behavior
```
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//a[@title='Clear Extensions Search Results']"}
  (Session info: chrome=102.0.5005.167)
```

## Steps to Reproduce the Problem
```
const sideBar = await (await new ActivityBar().getViewControl('Extensions')).openView();
const titlePart = sideBar.getTitlePart();
const actionButton = await titlePart.getAction('Clear Extensions Search Results');
if (actionButton.isEnabled()) {
    await actionButton.click();
}
```

## Specifications

  - VSCode version: 1.74.2
  - ExTester version: 5.3.0
  - Platform: 
      - [x] Linux
      - [ ] macOS
      - [ ] Windows

### PR DESCRIPTION
**Pull request by outscale-mdr**
Before submitting your PR, please review the following checklist:

- [ ] **CONSIDER** adding a new test if your PR resolves an issue.
- [x] **DO** keep pull requests small so they can be easily reviewed.
- [x] **DO** make sure tests pass.
- [x] **DO** make sure any public APIs changes are documented.
- [x] **DO** make sure not to introduce any compiler warnings.

Before merging the PR:

- [ ] **CHECK** continuous integration of `main` branch is green.
- [ ] **CHECK** pull request check job is green.
- [ ] **CHECK** all pull request questions/requests are resolved.
- [ ] **WAIT** till PR is approved by at least 1 committer.

Fix #605

See Screenshot for proof: 
Capture d’écran 2024-01-08 à 15 43 50

### CODE REVIEW

**Comment by outscale-mdr** [comment]
Do I correct the name `actionContstructor` or not  as well ?

**Comment by djelinek** [comment]
Hello @outscale-mdr sorry I am late, I needed to finish another projects stream first, but I am back. Thank you for you PR 🙂  lets take a look what we have here...



> Do I correct the name `actionContstructor` or not as well ?

I would expect `actionConstructor`

**Comment by djelinek** [comment]
oh okay.. taking back.. you did right, because there is a typo in codebase --> nice contrib + nice catch of little mistake 👍🏻  would you be interested in to provide another PR with fox for this typo also? 🙂

**Comment by djelinek** [comment]
okay you are right, there is a typo mistake in codebase - https://github.com/redhat-developer/vscode-extension-tester/blob/main/page-objects/src/locators/locators.ts#L224

nice PR + nice catch 👍🏻  would you interested in to provide another PR with fix for this typo? 🙂

**Comment by outscale-mdr** [comment]
Hello @djelinek 

Yes of course. I will open a new PR for that

**Review by djelinek — APPROVED** [review]

**Pull request merged**
