### PR TITLE
Use clipboard instead of typing text into dialogs

### LINKED ISSUE #13: Support different keyboard layout
Depending on the keyboard layout of the user launching the test, different behavior occurs with keypress.
It would be better to find a keypress library taking care of the keyboard layout so that all users can launch tests locally.

### PR DESCRIPTION
**Pull request by jrichter1**
should fix #13 since it no longer uses characters that would change keycodes between most layouts

@apupier would you care to try this out?

### CODE REVIEW

**Comment by apupier** [comment]
it is working far better, thanks!

i still have 2 tests failing on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/136 
- one is a known issue in Camel language Server, so not related
- the other I don't know if it is related or not:
```
2) Camel LSP - XML DSL Support
       Auto-completion for referenced components IDs
         Auto-completion for referenced ID of "direct" component:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (out/ui-test/xml_completion_support.js:162:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/ui-test/xml_completion_support.js:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by djelinek** [comment]
it shouldn't be related to problems with keyboard layouts. It looks more as wait issue in tests.

**Comment by apupier** [comment]
> it shouldn't be related to problems with keyboard layouts. It looks more as wait issue in tests.

tested that it is effectively the case (thanks to point where I needed to change the wait time).

So this PR is fixing the issue.

**Comment by jrichter1** [comment]
Thanks for the feedback guys :)

**Pull request merged**
