### PR TITLE
#193 - Take screenshot when mocha hook fails

### LINKED ISSUE #193: Take screenshots on error in beforeAll/afterAll methods
it will be convenient to take a screenshots in beforeAll and afterAll when an error occurs

### PR DESCRIPTION
**Pull request by mlorinc**
Resolves #193.

Signed-off-by: Marian Lorinc <mlorinc@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@mlorinc Can we have the CI fixed?

**Comment by mlorinc** [comment]
As Dominik mentioned it is currently failing on CI and OS X environments. The problem is the cause of problem is unknown for now.

**Comment by mlorinc** [comment]
PR is ready for a review. New feature is opt-in. To use new feature, add the following import statement:

```js
import { before } from 'vscode-extension-tester'
```;

Imported hooks are Mocha hook wrappers which can take screenshots on failure.

**Comment by djelinek** [comment]
> PR is ready for a review. New feature is opt-in. To use new feature, add the following import statement:
> 
> ```js
> import { before } from 'vscode-extension-tester';
> ```
> 
> Imported hooks are Mocha hook wrappers which can take screenshots on failure.

I would say it would be nice to have that mentioned somewhere in WIKI page... WDYT @odockal  ?

**Comment by odockal** [comment]
> > PR is ready for a review. New feature is opt-in. To use new feature, add the following import statement:
> > ```js
> > import { before } from 'vscode-extension-tester';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Imported hooks are Mocha hook wrappers which can take screenshots on failure.
> 
> I would say it would be nice to have that mentioned somewhere in WIKI page... WDYT @odockal ?

I am definitely for adding this to wiki as well. We can do it in separate PR though ;). Besides that. I would like the idea of having the feature enabled by default. If that is possible. Also we can do it another PR. 

So LGTM, plus consider using this feature by default (not really sure how to do it).

**Review by odockal — APPROVED** [review]

**Review by djelinek — APPROVED** [review]

**Pull request merged**
