### PR TITLE
feat(cli): Allows instaling pre-release version of extensions

### PR DESCRIPTION
**Pull request by serhergz**
feat(cli): This change allows to install pre-release versions of extensions into the test instance.
This change is useful for automation testing where you want to prevent a dependency breakage detecting it as soon as possible. There are no test in the suite for the cli commands, i tested locally.

### CODE REVIEW

**Comment by djelinek** [comment]
reported by SonarCloud

image

**Comment by djelinek** [comment]
> feat(cli): This change allows to install pre-release versions of extensions into the test instance. This change is useful for automation testing where you want to prevent a dependency breakage detecting it as soon as possible. There are no test in the suite for the cli commands, i tested locally.

Thank you for your PR! I will work on reviewing your code ASAP. 

Could you please also find/open appropriate issue (request)?

Thank you! 🙂

**Comment by serhergz** [comment]
Hi Dominik, I created this issue https://github.com/redhat-developer/vscode-extension-tester/issues/1583, 
And i will fix your comment.

**Comment by serhergz** [comment]
I will close this PR and create a clean one

**Pull request closed without merging**
