### PR TITLE
Add placeholder min/max values to --code_version option, fixes #480

### LINKED ISSUE #480: Add placeholder min/max values to --code_version option
As new versions vscode appear often and they are likely to break extest, we need to expose the minimum and the maximum version of vscode that is supported by current version, so users of this tool can use them in their testing pipelines.

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by djelinek** [comment]
@odockal What about to change also GH PR check pipelines to use min/max?

in theory we should use in automation only 3 versions
- min
- max
- insider (to know what will be support for next release)

WDYT?

**Comment by odockal** [comment]
@djelinek Sounds good!

**Review by mlorinc — APPROVED** [review]

**Comment by djelinek** [comment]
@odockal what do you think about to also move `macos` and `win` PR check pipelines from `latest` to `max` too?

**Review by djelinek — APPROVED** [review]

**Comment by odockal** [comment]
@djelinek that is great suggestion, I have to think that through though... I would probably address that in another PR.

**Pull request merged**
